language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: cZ5BC53r2Scv1wJuzJlNx9nB1/iJMsy/dXt0I1TQ10OpB5sCSFmjCQszwiIeLT4XVH9GOnYTVRPaT89kQbZXGflQGM0u3Q0Cv2UO/FzXYGtSZ+aB1xpa6bFqr+dV0SgBFTcklIzRIqamiyyKAnQvJz28gNfqhhX1fxwwO/Kwd30Qi7Qp9Xgs57XjpDRr88ptDGxxp9vBw6v4ZDdOPh45JR6CYWT2ErCfGihhstytWLYh3CZIkQ54POJD4nOOwFeSOFXcDBI5AlrfzPNIpBiSRgCd1wZKwjrBeblaaZqphNm2jjfCiC3rTEc2CtewrxStgoPp2WE7MNVxfyQwJkBpA7Y/Anq7qcLnEMFw5QXeMOasL6YsBdDBaMClgiWl+zxd07qXZllTMQeAAibl4vyuZjntZfloHhBASbpD/0w3fqr5p6rhfvVVVxp7vQKMNdKSMfTJSMvRZwBsQFPqPqfpZa9hO0L1Et2GiWXXC7O/f87eJCnbb5ki6JKwsSR0ZXED44q/5GiawM7cLIXG4gAJJd4mk+/QpCWN5V5GfS4xd0/0toUC5EXRfc80TCv/exfBsicsqSG5EWNKjJaS/FFLWPB5X87MdZCJUyJzzEDgI5RcQHl+lFhMolfdHJTaCjlIMF5W1FZ3YsMaZPdmjF3nraWyPInuShcN6sbZqah55C8=
  app: sleepy-atoll-60170
  on:
    repo: AdamJDuggan/abacus
